FROM php:5.6-fpm

RUN docker-php-ext-install mysql mysqli pdo_mysql

# FPM 이 컨테이너 밖(호스트 nginx)에서 붙을 수 있도록
RUN sed -i 's/^listen = .*/listen = 9000/' /usr/local/etc/php-fpm.d/www.conf

WORKDIR /lunar/ln_mes/ts/ln_mes_taesung
